/*
 * 
 */
package corredor;

import javax.swing.ImageIcon;

/**
 *
 * @author f865
 */
public class JogoMenu extends javax.swing.JFrame {
    
   
    /**
     * Creates new form JogoCorredor
     */
    public JogoMenu() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPersonagens = new javax.swing.ButtonGroup();
        painelImagem = new javax.swing.JPanel();
        etNivel = new javax.swing.JLabel();
        etTextoAtaque = new javax.swing.JLabel();
        etAtaque = new javax.swing.JLabel();
        etCarateristicas = new javax.swing.JLabel();
        etPersonagem2 = new javax.swing.JLabel();
        etPersonagem1 = new javax.swing.JLabel();
        etPersonagem3 = new javax.swing.JLabel();
        escolhaPersonagem1 = new javax.swing.JRadioButton();
        escolhaPersonagem2 = new javax.swing.JRadioButton();
        escolhaPersonagem3 = new javax.swing.JRadioButton();
        etTextoDefesa = new javax.swing.JLabel();
        etDefesa = new javax.swing.JLabel();
        painelControlos = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etNivel.setText("Escolha a personagem");

        etTextoAtaque.setText("Ataque:");

        etAtaque.setText("0");

        etCarateristicas.setText("Caraterísticas:");

        etPersonagem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etPersonagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/feiticeira.png"))); // NOI18N
        etPersonagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        etPersonagem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/guerreiro.png"))); // NOI18N
        etPersonagem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        etPersonagem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etPersonagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ladrao.png"))); // NOI18N
        etPersonagem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        grupoPersonagens.add(escolhaPersonagem1);
        escolhaPersonagem1.setText("Guerreiro");

        grupoPersonagens.add(escolhaPersonagem2);
        escolhaPersonagem2.setText("Feiticeiro");

        grupoPersonagens.add(escolhaPersonagem3);
        escolhaPersonagem3.setText("Ladrão");

        etTextoDefesa.setText("Defesa:");

        etDefesa.setText("0");

        javax.swing.GroupLayout painelImagemLayout = new javax.swing.GroupLayout(painelImagem);
        painelImagem.setLayout(painelImagemLayout);
        painelImagemLayout.setHorizontalGroup(
            painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etNivel)
                    .addGroup(painelImagemLayout.createSequentialGroup()
                        .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escolhaPersonagem1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etPersonagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escolhaPersonagem2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escolhaPersonagem3)
                            .addComponent(etPersonagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(etCarateristicas)
                    .addGroup(painelImagemLayout.createSequentialGroup()
                        .addComponent(etTextoAtaque)
                        .addGap(18, 18, 18)
                        .addComponent(etAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etTextoDefesa)
                        .addGap(18, 18, 18)
                        .addComponent(etDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        painelImagemLayout.setVerticalGroup(
            painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etNivel)
                .addGap(18, 18, 18)
                .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPersonagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPersonagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escolhaPersonagem1)
                    .addComponent(escolhaPersonagem2)
                    .addComponent(escolhaPersonagem3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etCarateristicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etTextoAtaque)
                    .addComponent(etAtaque)
                    .addGroup(painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etTextoDefesa)
                        .addComponent(etDefesa)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout painelControlosLayout = new javax.swing.GroupLayout(painelControlos);
        painelControlos.setLayout(painelControlosLayout);
        painelControlosLayout.setHorizontalGroup(
            painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );
        painelControlosLayout.setVerticalGroup(
            painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlosLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelControlos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(painelControlos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton escolhaPersonagem1;
    private javax.swing.JRadioButton escolhaPersonagem2;
    private javax.swing.JRadioButton escolhaPersonagem3;
    private javax.swing.JLabel etAtaque;
    private javax.swing.JLabel etCarateristicas;
    private javax.swing.JLabel etDefesa;
    private javax.swing.JLabel etNivel;
    private javax.swing.JLabel etPersonagem1;
    private javax.swing.JLabel etPersonagem2;
    private javax.swing.JLabel etPersonagem3;
    private javax.swing.JLabel etTextoAtaque;
    private javax.swing.JLabel etTextoDefesa;
    private javax.swing.ButtonGroup grupoPersonagens;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel painelControlos;
    private javax.swing.JPanel painelImagem;
    // End of variables declaration//GEN-END:variables
}
