/*
 * 
 */
package corredor;

import javax.swing.ImageIcon;

/**
 *
 * @author gm
 */
public class JogoCorredor extends javax.swing.JFrame {
    
    private ImageIcon imagem1;
    private ImageIcon imagem2;
    private int imagemAtual;
    private Corredor corr;
    private int posAtual;
    /**
     * Creates new form JogoCorredor
     */
    public JogoCorredor() {
        initComponents();
        imagem1 = new javax.swing.ImageIcon(getClass().getResource("/imagens/corredor.png"));
        imagem1.setDescription("1");
        imagem2 = new javax.swing.ImageIcon(getClass().getResource("/imagens/corredor2.png"));
        imagem2.setDescription("2");
        etImagem.setIcon(imagem1);
        imagemAtual = 1;
        
        corr = new Corredor(10);
        etComprimento.setText("/"+corr.obterComprimento());
        posAtual = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelImagem = new javax.swing.JPanel();
        etImagem = new javax.swing.JLabel();
        painelControlos = new javax.swing.JPanel();
        botMover = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        etPosTexto = new javax.swing.JLabel();
        etComprimento = new javax.swing.JLabel();
        etNivel = new javax.swing.JLabel();
        etPos = new javax.swing.JLabel();
        etTextoPersonagem = new javax.swing.JLabel();
        etPersonagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelImagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/corredor2.png"))); // NOI18N
        etImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelImagem.add(etImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(painelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        botMover.setText("Mover");
        botMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMoverActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        etPosTexto.setText("Posição:");

        etComprimento.setText("/ 0");

        etNivel.setText("Nível:");

        etPos.setText("1");

        etTextoPersonagem.setText("Personagem:");

        etPersonagem.setText("nome (classe)");

        javax.swing.GroupLayout painelControlosLayout = new javax.swing.GroupLayout(painelControlos);
        painelControlos.setLayout(painelControlosLayout);
        painelControlosLayout.setHorizontalGroup(
            painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelControlosLayout.createSequentialGroup()
                        .addComponent(etNivel)
                        .addGap(202, 202, 202)
                        .addComponent(etPosTexto)
                        .addGap(18, 18, 18)
                        .addComponent(etPos)
                        .addGap(18, 18, 18)
                        .addComponent(etComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelControlosLayout.createSequentialGroup()
                        .addGroup(painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etTextoPersonagem)
                            .addComponent(etPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(botMover))))
        );
        painelControlosLayout.setVerticalGroup(
            painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etNivel)
                    .addComponent(etPosTexto)
                    .addComponent(etPos)
                    .addComponent(etComprimento))
                .addGap(12, 12, 12)
                .addGroup(painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelControlosLayout.createSequentialGroup()
                        .addComponent(etTextoPersonagem)
                        .addGap(6, 6, 6)
                        .addComponent(etPersonagem))
                    .addGroup(painelControlosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(painelControlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelControlosLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(botMover, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        getContentPane().add(painelControlos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 284, 400, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMoverActionPerformed
        if (posAtual < corr.obterComprimento()-1) {
            if(imagemAtual == 1) {
                etImagem.setIcon(imagem2);
                imagemAtual = 2;
            }
            else {
                etImagem.setIcon(imagem1);
                imagemAtual = 1;
            }
            posAtual++;
            etPos.setText(""+ (posAtual+1));
            if (corr.posTemInimigo(posAtual)) {
                Inimigo ini = corr.obterInimigo(posAtual);
                String fichImag = ini.obterNomeImagem();
                ImageIcon imagemIni = new javax.swing.ImageIcon(getClass().getResource("/imagens/"+fichImag));
                
                
                //((ImageIcon) etImagem.getIcon()).getImage().getGraphics().drawImage(imagemIni.getImage(), 0,0,null);
                etImagem.setIcon(imagemIni);
               // etImagem.getGraphics().drawImage(imagemIni.getImage(),0,0,null);
                
            }
        }
    }//GEN-LAST:event_botMoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoCorredor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botMover;
    private javax.swing.JLabel etComprimento;
    private javax.swing.JLabel etImagem;
    private javax.swing.JLabel etNivel;
    private javax.swing.JLabel etPersonagem;
    private javax.swing.JLabel etPos;
    private javax.swing.JLabel etPosTexto;
    private javax.swing.JLabel etTextoPersonagem;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel painelControlos;
    private javax.swing.JPanel painelImagem;
    // End of variables declaration//GEN-END:variables
}
