/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package palavra;

import javax.swing.JOptionPane;

/**
 *
 * @author administrador
 */
public class JogoAdivinharPalavra extends javax.swing.JFrame {
    private AdivinharPalavra palavra;
    private int tentativas;
    /**
     * Creates new form Jogo1
     */
    public JogoAdivinharPalavra() {
        initComponents();
        tentativas = 10;
        etRestantes.setText(""+tentativas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etTitulo = new javax.swing.JLabel();
        botInserirPalavra = new javax.swing.JButton();
        etPalavra = new javax.swing.JLabel();
        botLetra = new javax.swing.JButton();
        etTentativas = new javax.swing.JLabel();
        etRestantes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etTitulo.setText("Adivinhar a Palavra");

        botInserirPalavra.setText("Inserir Palavra");
        botInserirPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInserirPalavraActionPerformed(evt);
            }
        });

        etPalavra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botLetra.setText("Adivinhar Letra");
        botLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLetraActionPerformed(evt);
            }
        });

        etTentativas.setText("Tentativas:");

        etRestantes.setText("10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etTentativas)
                                .addGap(18, 18, 18)
                                .addComponent(etRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botLetra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(botInserirPalavra)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTitulo)
                .addGap(18, 18, 18)
                .addComponent(etPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etTentativas)
                    .addComponent(etRestantes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botInserirPalavra)
                    .addComponent(botLetra))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botInserirPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInserirPalavraActionPerformed
        String p = JOptionPane.showInputDialog(this,"Introduza a palavra a adivinhar:");
        palavra = new AdivinharPalavra(p);
        etPalavra.setText(palavra.obterLetrasAdivinhadas());
        tentativas = 10;
        etRestantes.setText(""+tentativas);
    }//GEN-LAST:event_botInserirPalavraActionPerformed

    private void botLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLetraActionPerformed
        if (tentativas > 0) {
            String p = JOptionPane.showInputDialog(this,"Letra:");
            if (palavra.adivinharLetra(p.charAt(0))) {
                etPalavra.setText(palavra.obterLetrasAdivinhadas());
            }
            else {
                tentativas--;
                etRestantes.setText(""+tentativas);
            }

            if (palavra.palavraAdivinhada()) {
                JOptionPane.showMessageDialog(this,"Parabéns!");
            }
            else
                if (tentativas == 0) {
                    JOptionPane.showMessageDialog(this,"Perdeu!");    
                }
        }
    }//GEN-LAST:event_botLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinharPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinharPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinharPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinharPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoAdivinharPalavra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botInserirPalavra;
    private javax.swing.JButton botLetra;
    private javax.swing.JLabel etPalavra;
    private javax.swing.JLabel etRestantes;
    private javax.swing.JLabel etTentativas;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
